/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function OG(props) {
  const { nodes, materials } = useGLTF("/OG.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[-0.26, 4.79, -0.21]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh004.geometry}
          material={materials["THippie.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh004_1.geometry}
          material={materials.Black_Piano}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh004_2.geometry}
          material={materials.Shoe1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh004_3.geometry}
          material={materials.THippieAlphaa}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/OG.glb");