/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function VibranceSplash(props) {
  const { nodes, materials } = useGLTF("/Vibrance Splash.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[0, 2.32, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh002.geometry}
          material={materials["THippie.Translucent"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh002_1.geometry}
          material={materials["Material.024"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh002_2.geometry}
          material={materials.THippie}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Vibrance Splash.glb");
